### ISSUE TITLE
Include PI information

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#29]

**Comment by wdduncan** [comment]
The PI table needs to be included in the data dump. If this is not possible, I might be able to grab the PI name from the analysis project table.

**Comment by dehays** [comment]
@wdduncan  I am looking at the data from GOLD (aka 'the data dump') . and the PI information is there though I can see how it might not be easy to see because the relevant field on the STUDY table is not called PI it is called CONTACT_ID.  That is the FK to the CONTACT table.

Example:  If I look at the study record for STUDY_ID = 110132 (GOLD_ID is Gs0110132) . I see a CONTACT_ID of 100043.  In the CONTACT table, the record where CONTACT_ID = 103865 is the record for Matthias Hess - the PI for that study.

**Comment by wdduncan** [comment]
Thanks @dehays 
In the CONTACT table, I see two contact_ids for Matthias Hess: 100043 and 115767

**Comment by dehays** [comment]
@wdduncan But in the case of study 110132 the contact record to associate as PI is the one the study record points to, 100043.

There is another thing that Reddy reminded me of today - both the study and the project will have PIs and they are not required to be the same.  I don't think that case occurs in the 13 studies being used for the NMDC pilot, but with GOLD as your source for metadata that will need to be accounted for in the future.

**Comment by wdduncan** [comment]
PI name has been added at both the study and project level. For now, it is a characteristic of the study/project. We look into developing a more adequate schema at a later iteration.
