### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-metadata#317]
Whether BSD 3-clause (the standard when I was at LBL), Apache 2 (clear contributor agreement w/o additional text), etc., this repo should have a `LICENSE` to be clear about *how* it is open-source.

**Comment by cmungall** [comment]
Agreed - I think a CC license is more appropriate for the schema content - include both? I favor CC-0 for schema

**Comment by wdduncan** [comment]
I thought @kfagnan was looking into licensing? We brought this up a while ago (sometime last year) on the weekly calls.

**Comment by kfagnan** [comment]
Yep, thanks for surfacing this again. I actually asked Set to assign this to me as an action for this sprint. IPO has indicated we can use the Apache license. 

We actually got a bit held up by one license for NMDC or different licenses for different facets of the project. We can proceed either way. However, there are some aspects of the workflows we should not distribute because the 3rd party software has restrictions. So we need to decide as a team what we want to do with that edge case (maybe just make the workflows executable in EDGE?). If we aren't redistributing the software, then we don't need to license it.
